name = "connector-test-modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a43aaa67de21d2b3d91c6515707904a0c6fe8a395cedb1773720730f99c474a"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
