name = "connector-test-modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f4d6dd154f1be42ff583b68fee32d167a48c928a44db4c82e19f637e0d387c4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
