name = "Test Modpack"
author = "ashcraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bef1d34d70807b75a956acf290c93ba9f05d4772b2ff4675de1b38759640a3d1"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
