name = "Test Modpack"
author = "ashcraft"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b7e23e5567eaa2b814387bfbfbb219f121b469acaf658ec8dffcc86858c9e030"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.209"
