name = "SoulCraft 304"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7accd8827d338a76592a40a2505a5b898c1c1b5d4bbba39f49af9dd4637432e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.205"
