name = "SoulCraft 304"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1dc30684c8d5f16975c5a5e3427adff4db9ba9cd52ebc55809c8dd4bfd87b5f"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.205"
