name = "SoulCraft 304"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e46e1f7394412699fcf78badbfda3135799d08d47cd5b4e98a0576152eaaeac"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.205"
